apiVersion: apps/v1
kind: Deployment
metadata:
  name: cai-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cai-manager
  template:
    metadata:
      labels:
        app: cai-manager
    spec:
      serviceAccountName: cai-manager-sa
      containers:
      - name: api
        image: docker.io/umesh1212/cai-manager:v54
        imagePullPolicy: IfNotPresent
        env:
        - name: DEEPSEEK_API_KEY
          value: "sk-"
        - name: DEEPSEEK_API_URL
          value: "https://api.deepseek.com/v1"
        - name: OPENAI_API_KEY
          value: "sk-..."
        - name: CAI_STEAM
          value: "true"
        - name: CAI_IMAGE
          value: "neptune1212/kali-cai:amd64"
        - name: CAI_AGENTS
          value: "redteam_agent,blueteam_agent"
        - name: WEBHOOK_URL
          value: "http://172.18.254.200:8000/api/webhooks"
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: file-storage
          mountPath: /app/storage
      volumes:
      - name: file-storage
        persistentVolumeClaim:
          claimName: cai-manager-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cai-manager-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/data/cai-manager
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cai-manager-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
