[project]
name = "mcp-client-server-chat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.116.1",
    "fastmcp>=2.11.3",
    "google-generativeai>=0.8.5",
    "mcp[cli]>=1.13.1",
]
