apiVersion: work.open-cluster-management.io/v1
kind: ManifestWork
metadata:
  name: demo-job-east
  namespace: east
spec:
  workload:
    manifests:
      - apiVersion: batch/v1
        kind: Job
        metadata:
          name: demo-job
          namespace: demo-ns
        spec:
          template:
            metadata:
              labels:
                job: demo-job
            spec:
              restartPolicy: Never
              containers:
                - name: demo
                  image: 'busybox:1.36'
                  command:
                    - sh
                    - '-c'
                    - echo hello from job && sleep 10
